### ISSUE TITLE
"app stopped working" after receiving sms

### ISSUE THREAD

**Issue by danielllek** [warren-bank/Android-SMS-Automatic-Reply-GPS#1]
After I receive sms from whitelisted number, telephone gets GPS fix, and than I get message "SMS my GPS stopped working".
Return sms with location is not sent.
Android 7.1.1 (xperia z5 compact).

Any ideas what can be wrong?

**Comment by danielllek** [comment]
Connected logcat to my phone:
```
2020-05-01 21:02:19.405 22895-22895/com.github.warren_bank.sms_automatic_reply_gps I/SMSReceiver: SMS received.
    from: +48.....
    message: .......
2020-05-01 21:02:57.737 22895-22895/com.github.warren_bank.sms_automatic_reply_gps D/AndroidRuntime: Shutting down VM
2020-05-01 21:02:57.738 22895-22895/com.github.warren_bank.sms_automatic_reply_gps E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.github.warren_bank.sms_automatic_reply_gps, PID: 22895
    java.lang.NoSuchMethodError: No virtual method getBearingAccuracyDegrees()F in class Landroid/location/Location; or its super classes (declaration of 'android.location.Location' appears in /system/framework/framework.jar)
        at com.github.warren_bank.sms_automatic_reply_gps.event.GPSSender$SMSLocationListener.getDirection(GPSSender.java:107)
        at com.github.warren_bank.sms_automatic_reply_gps.event.GPSSender$SMSLocationListener.onLocationChanged(GPSSender.java:47)
        at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:297)
        at android.location.LocationManager$ListenerTransport.-wrap0(LocationManager.java)
        at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:242)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:241)
        at android.app.ActivityThread.main(ActivityThread.java:6274)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by warren-bank** [comment]
nice catch! ..I don't know how I messed up [this statement](https://github.com/warren-bank/Android-SMS-Automatic-Reply-GPS/blob/6ea0c2e920b71811c39730e653948b92ece0b52f/android-studio-project/SMS-my-GPS/src/main/java/com/github/warren_bank/sms_automatic_reply_gps/event/GPSSender.java#L103) by checking for the wrong SDK version (ie: 23 instead of [26](https://developer.android.com/reference/android/location/Location#getBearingAccuracyDegrees())):

```java
  float accuracy = (Build.VERSION.SDK_INT >= 23)
    ? location.getBearingAccuracyDegrees()
    : Float.MIN_VALUE;
```

..I'll push an update shortly. Thanks for letting me know :)

**Comment by danielllek** [comment]
Found it few minutes ago too :-D
Works with the fix.

**Comment by warren-bank** [comment]
Whew!.. glad to hear it :) Again, sorry for the bug.. that was totally my bad.

**Comment by danielllek** [comment]
I can post PR if you like.

**Comment by warren-bank** [comment]
not necessary.. it's literally a 1 character fix :P

..I'm in the middle of doing something else atm, but I'll definitely post this before tomorrow

**Comment by warren-bank** [comment]
just [released](https://github.com/warren-bank/Android-SMS-Automatic-Reply-GPS/releases/tag/v2.1.6) the apk for v2.1.6

thanks again for finding this bug.. much appreciated!
